// AUTO-GENERATED by scripts/regen-static-user-skills.cjs.
// Source: .claude/skills/<name>/SKILL.md.
// Regenerate: node scripts/regen-static-user-skills.cjs
// Do not edit by hand; freshness is enforced by
// packages/cli/src/__tests__/static-user-skills-freshness.test.ts.

import type { StaticUserSkillName } from "./types.js";

export const STATIC_USER_SKILL_CONTENT: Record<StaticUserSkillName, string> = {
  "duck": "---\nname: duck\ndescription: By-hand trigger only. When the user types /duck, explain the current topic / latest answer to a cute CEO non-coder duck. Do not auto-trigger.\n---\n\nExplain to a cute ceo non coder duck please.\n",
  "grill-me": "---\nname: grill-me\ndescription: Interview the user relentlessly about a plan or design until reaching shared understanding, resolving each branch of the decision tree. Use when user wants to stress-test a plan, get grilled on their design, or mentions \"grill me\".\n---\n\n## Grill loop\n\nInterview me relentlessly about every aspect of this plan until we reach a shared understanding. Walk down each branch of the design tree, resolving dependencies between decisions one-by-one. For each question, provide your recommended answer.\n\nAsk the questions one at a time.\n\nIf a question can be answered by exploring the codebase, explore the codebase instead.\n",
};
