import fs from "node:fs";
import path from "node:path";
import type { Compiler } from "@teamagent/ports";
import type { KnowledgeEntry } from "@teamagent/types";

const HEADER = `# .cursorrules — generated by TeamAgent
# DO NOT EDIT MANUALLY. Re-run: teamagent compile --target cursor
`;

/**
 * Compiler<string> adapter that emits a Cursor .cursorrules file from knowledge entries.
 *
 * Format: one rule block per entry — correct_pattern + reasoning.
 * Pure compile(); writeToFile() handles the IO.
 */
export class CursorRulesCompiler implements Compiler<string> {
  constructor(private readonly outPath: string) {}

  compile(entries: KnowledgeEntry[]): string {
    if (entries.length === 0) return HEADER.trimEnd() + "\n";

    const blocks = entries.map((e) => {
      const lines: string[] = [];
      lines.push(`## Rule: ${e.id}`);
      if (e.trigger) lines.push(`# Trigger: ${e.trigger}`);
      lines.push(e.correct_pattern);
      if (e.reasoning) lines.push(`# Reason: ${e.reasoning}`);
      return lines.join("\n");
    });

    return HEADER + "\n" + blocks.join("\n\n") + "\n";
  }

  writeToFile(entries: KnowledgeEntry[]): void {
    const dir = path.dirname(this.outPath);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(this.outPath, this.compile(entries), "utf-8");
  }
}
