import { describe, it, expect } from "vitest";
import { extractRuleBullets } from "../claude-md-parser.js";

describe("extractRuleBullets", () => {
  it("empty input → []", () => {
    expect(extractRuleBullets("")).toEqual([]);
  });

  it("no bullets → []", () => {
    const md = "# Title\n\nJust prose about the project.\n\n## Section";
    expect(extractRuleBullets(md)).toEqual([]);
  });

  it("extracts - bullets", () => {
    const md = `## Rules
- Use fetch, not axios
- Run pnpm test before push`;
    expect(extractRuleBullets(md)).toEqual([
      "Use fetch, not axios",
      "Run pnpm test before push",
    ]);
  });

  it("extracts * bullets", () => {
    const md = `* rule A\n* rule B`;
    expect(extractRuleBullets(md)).toEqual(["rule A", "rule B"]);
  });

  it("extracts + bullets", () => {
    expect(extractRuleBullets("+ a\n+ b")).toEqual(["a", "b"]);
  });

  it("extracts numbered bullets", () => {
    const md = `1. first rule
2. second rule
10. tenth rule`;
    expect(extractRuleBullets(md)).toEqual([
      "first rule",
      "second rule",
      "tenth rule",
    ]);
  });

  it("joins indented continuation lines into the same bullet", () => {
    const md = `- Don't use axios
  because the project prefers zero-dep
  and fetch is native`;
    expect(extractRuleBullets(md)).toEqual([
      "Don't use axios because the project prefers zero-dep and fetch is native",
    ]);
  });

  it("blank line terminates a bullet", () => {
    const md = `- rule one
  continues here

- rule two`;
    expect(extractRuleBullets(md)).toEqual([
      "rule one continues here",
      "rule two",
    ]);
  });

  it("skips <!-- TEAMAGENT:START --> block entirely", () => {
    const md = `## Project rules
- human-authored rule

<!-- TEAMAGENT:START - auto -->
- auto-generated rule that must NOT be re-imported
- another auto rule
<!-- TEAMAGENT:END -->

- another human rule`;
    expect(extractRuleBullets(md)).toEqual([
      "human-authored rule",
      "another human rule",
    ]);
  });

  it("ignores bullets inside fenced code blocks", () => {
    const md = `## Config

\`\`\`yaml
- this-is-yaml-not-a-rule
- also-config
\`\`\`

- real rule after code block`;
    expect(extractRuleBullets(md)).toEqual(["real rule after code block"]);
  });

  it("ignores nested sub-bullets as continuation (they merge with parent)", () => {
    // Note: simple parser treats indented bullets as part of the parent bullet.
    // We don't need full markdown nesting for rule import.
    const md = `- parent rule
  - sub point explaining it`;
    const out = extractRuleBullets(md);
    expect(out).toHaveLength(1);
    expect(out[0]).toContain("parent rule");
    expect(out[0]).toContain("sub point");
  });

  it("handles mixed bullet styles", () => {
    const md = `- dash rule
* star rule
+ plus rule
1. numbered rule`;
    expect(extractRuleBullets(md)).toEqual([
      "dash rule",
      "star rule",
      "plus rule",
      "numbered rule",
    ]);
  });

  it("preserves inline formatting but trims surrounding whitespace", () => {
    const md = `- **Important**: use \`fetch\` with real care`;
    expect(extractRuleBullets(md)).toEqual([
      "**Important**: use `fetch` with real care",
    ]);
  });

  it("returns empty for a CLAUDE.md with only the TEAMAGENT block", () => {
    const md = `# My project
Some prose.

<!-- TEAMAGENT:START - auto -->
- x
- y
<!-- TEAMAGENT:END -->`;
    expect(extractRuleBullets(md)).toEqual([]);
  });

  it("real-world sample: mixed headers + rules + TEAMAGENT block", () => {
    const md = `# Project Guide
Welcome.

## Development conventions
- Use TypeScript strict mode
- Prefer pnpm over npm/yarn
- Run \`pnpm test\` before every commit

## Code style
- 2-space indent
- No trailing commas

<!-- TEAMAGENT:START - autogenerated -->
## Auto knowledge
- auto rule 1
- auto rule 2
<!-- TEAMAGENT:END -->

## Ops
1. Check the logs first
2. Escalate if the pager is paging`;
    const out = extractRuleBullets(md);
    expect(out).toEqual([
      "Use TypeScript strict mode",
      "Prefer pnpm over npm/yarn",
      "Run `pnpm test` before every commit",
      "2-space indent",
      "No trailing commas",
      "Check the logs first",
      "Escalate if the pager is paging",
    ]);
  });
});
